"""Generate scene bodies (demo/scenes/<id>.body.js) from a schemaVersion 2 storyboard.

Every action type maps to one prelude helper, so two agents with the same
storyboard produce the same body. A generated file starts with the marker
line below and is regenerated on every render; remove the marker to take a
body over by hand (only for logic the action list cannot express).
"""
import hashlib
import json
import re

GENERATED_MARK = "// @generated by dv.py from storyboard.json - remove this line to hand-edit"
SCENE_MARK = "// @scene "          # + scene hash: a hand-written body records which storyboard scene it was written for


def scene_hash(scene) -> str:
    """Hash of what a body depends on: url, waitFor, setup, steps (subtitles + actions). Not holds/dwell."""
    core = {"url": scene.get("url"), "waitFor": scene.get("waitFor"), "setup": scene.get("setup") or [],
            "steps": [{"subtitle": st.get("subtitle"), "actions": st.get("actions") or []} for st in scene.get("steps") or []]}
    return hashlib.sha256(json.dumps(core, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()[:12]


def body_scene_mark(text: str):
    m = re.search(r"^//\s*@scene\s+([0-9a-f]{12})", text, re.M)
    return m.group(1) if m else None


def hand_body(scene) -> str:
    """A body to take over by hand: same statements as the generated one, no @generated marker,
    plus the @scene marker so render can tell when the storyboard moved on without it."""
    gen = scene_body(scene).splitlines()[1:]
    return "\n".join([SCENE_MARK + scene_hash(scene),
                       "// hand-written body - keep the @scene line; render warns when the storyboard scene changes"] + gen) + "\n"


def js(v):
    return json.dumps(v, ensure_ascii=False)


def action_js(a):
    t = a["type"]
    tgt = js(a.get("target", ""))
    if t == "goto":
        return f"await page.goto(BASE + {js(a['url'])}); await page.waitForLoadState('networkidle');"
    if t == "click":
        return f"await click({tgt});"
    if t == "type":
        val = a["value"]
        expr = val if isinstance(val, str) and val.startswith("ACCOUNTS.") else js(val)
        return f"await typeText({tgt}, {expr}, {{ secret: {js(bool(a.get('secret')))} }});"
    if t == "hover":
        return f"await hoverOn({tgt}, {{ ms: {js(a.get('ms'))} }});" if a.get("ms") else f"await hoverOn({tgt});"
    if t == "scroll":
        opts = {k: a[k] for k in ("toRatio", "byPx", "axis", "ms") if k in a}
        return f"await scrollTo({tgt}, {js(opts)});"
    if t == "waitFor":
        if a.get("url"):
            return f"await waitFor({{ url: {js(a['url'])} }});"
        opts = {k: a[k] for k in ("state", "timeoutMs") if k in a}
        return f"await waitFor({tgt}, {js(opts)});"
    if t == "zoom":
        opts = {k: a[k] for k in ("scale", "ms") if k in a}
        return f"await zoom({tgt}, {js(opts)});"
    if t == "zoomOut":
        return "await zoomOut();"
    if t == "highlight":
        opts = {k: a[k] for k in ("label", "ms") if k in a}
        if "ms" in opts:
            opts["durationMs"] = opts.pop("ms")
        return f"await highlight({tgt}, {js(opts)});"
    if t == "chapter":
        return f"await chapter({js(a['title'])}, {js({k: a[k] for k in ('description', 'durationMs') if k in a})});"
    if t == "drag":
        opts = {"mode": a.get("mode", "pointer")}
        for k in ("ms", "steps", "pauseMs", "fromOffset", "toOffset"):
            if k in a:
                opts[k] = a[k]
        return f"await drag({js(a['source'])}, {tgt}, {js(opts)});"
    if t == "dropFile":
        return f"await dropFile({tgt}, {js(a['files'])});"
    if t == "resize":
        return f"await resize({tgt}, {js({k: a[k] for k in ('dx', 'dy') if k in a})});"
    if t == "slide":
        return f"await slide({tgt}, {js(a['value'])});"
    if t == "pan":
        return f"await pan({tgt}, {js({k: a[k] for k in ('dx', 'dy') if k in a})});"
    if t == "wheelZoom":
        return f"await wheelZoom({tgt}, {js({k: a[k] for k in ('deltaY', 'steps') if k in a})});"
    if t == "key":
        return f"await key({js(a['combo'])});"
    if t == "dblclick":
        return f"await dblclick({tgt});"
    if t == "rightClick":
        return f"await rightClick({tgt});"
    if t == "waitStream":
        opts = {k: a[k] for k in ("until", "attr", "value", "stableMs", "timeoutMs") if k in a}
        return f"await waitStream({tgt}, {js(opts)});"
    raise ValueError(f"no body mapping for action type {t}")


def scene_body(scene):
    lines = [GENERATED_MARK]
    # Off-camera setup: navigate and run setup actions before recording starts.
    # Scenes share a browser session; a goto that only changes the hash would keep the
    # SPA's in-memory state from the previous scene, so leave the document first.
    lines.append("await page.goto('about:blank');")
    lines.append(f"await page.goto(BASE + {js(scene['url'])});")
    lines.append("await page.waitForLoadState('networkidle');")
    if scene.get("waitFor"):
        lines.append(f"await waitFor({js(scene['waitFor'])});")
    for a in scene.get("setup") or []:
        lines.append(action_js(a))
    lines.append("// ---record---")
    for i, st in enumerate(scene["steps"]):
        sub = st["subtitle"]
        opts = {"emphasis": sub["emphasis"]} if sub.get("emphasis") else {}
        body = "\n".join("  " + action_js(a) for a in (st.get("actions") or []))
        work = f"async () => {{\n{body}\n}}" if body else "null"
        lines.append(f"await subtitleSpan({js(sub['text'])}, HOLD[{i}], {work}, {js(opts)});")
    # The scene runs at least its planned dwellMs, so clip lengths match the storyboard.
    lines.append("await padTo(DWELL);")
    return "\n".join(lines) + "\n"


def intro_body(intro):
    return (GENERATED_MARK + "\n" +
            f"await intro({js({'title': intro.get('title'), 'tagline': intro.get('tagline'), 'brand': intro.get('brand'), 'durationMs': intro.get('holdMs', 2500)})});\n")


def outro_body(outro):
    return (GENERATED_MARK + "\n" +
            f"await outro({js({'title': outro.get('title'), 'tagline': outro.get('tagline'), 'brand': outro.get('brand'), 'cta': outro.get('cta'), 'durationMs': outro.get('holdMs', 3000)})});\n")


def is_generated(text: str) -> bool:
    return text.lstrip().startswith(GENERATED_MARK)
